# This file contains the Kubernetes Secret resource definition.
# It is used to store sensitive information such as passwords, OAuth tokens, SSH keys, etc.
# Secrets are base64 encoded and can be mounted as volumes or exposed as environment variables.
apiVersion: v1
kind: Secret
metadata:
  name: users-db-secret
  namespace: full-stack-deployment
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
