apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: full-stack-deployment
  labels:
    app: client
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000        # Exposes service on port 3000
      targetPort: 3000 # Forwards traffic to React container port (3000)
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: users-db
  namespace: full-stack-deployment
spec:
  selector:
    app: users-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: full-stack-deployment
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: full-stack-deployment
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: full-stack-deployment
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379