apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: default
data:
  FLASK_ENV: development
  APP_SETTINGS: project.config.DevelopmentConfig
  DATABASE_URL: postgres://postgres:postgres@users-db:5432/users_dev
  DATABASE_TEST_URL: postgres://postgres:postgres@users-db:5432/users_test

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
data:
  NODE_ENV: development
  REACT_APP_USERS_SERVICE_URL: http://users:5000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  default.conf: |
    server {
        listen 80;

        # Serve React static files
        location / {
            root /usr/share/nginx/html;
            try_files $uri /index.html;
        }

        # Route API calls to Flask backend
        location /api/ {
            proxy_pass http://users:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
