# This file contains the Kubernetes Secret resource definition.
# It is used to store sensitive information such as passwords, OAuth tokens, SSH keys, etc.
apiVersion: v1
kind: Secret
metadata:
  name: users-db-secret
  namespace: default
type: Opaque
data:
  username: cG9zdGdyZXNz
  password: cG9zdGdyZXNz