apiVersion: v1
kind: Service
metadata:
  name: users-db
  labels:
    app: users-db
spec:
  selector:
    app: users-db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80        # Exposes service on port 80
      targetPort: 3000 # Forwards traffic to React container port (3000)
      nodePort: 30001  # Exposes the service on a specific NodePort
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: users-db
spec:
  selector:
    app: users-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
