apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    alertmanager: main
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    receivers:
    - name: slack-notifications
      slack_configs:
      - api_url: '{{ "{{" }} .slack_url {{ "}}" }}'
        channel: '#alerts'
        send_resolved: true

    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: slack-notifications
