apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: prometheus-kube-prometheus-alertmanager
  namespace: monitoring
spec:
  configSecret: alertmanager-config
  secrets:
    - alertmanager-slack-config
