apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: redis-exporter
    meta.helm.sh/release-namespace: monitoring
    prometheus.io/port: "9121"
    prometheus.io/scrape: "true"
  creationTimestamp: "2025-05-10T17:27:42Z"
  labels:
    app: redis-exporter
    app.kubernetes.io/instance: redis-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-redis-exporter
    app.kubernetes.io/version: v1.69.0
    helm.sh/chart: prometheus-redis-exporter-6.10.2
  name: redis-exporter-prometheus-redis-exporter
  namespace: monitoring
  resourceVersion: "63432"
  uid: d701664d-65e5-4972-a385-3d6cc13ac18f
spec:
  clusterIP: 10.152.183.218
  clusterIPs:
  - 10.152.183.218
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9121
    protocol: TCP
    targetPort: 9121
  selector:
    app.kubernetes.io/instance: redis-exporter
    app.kubernetes.io/name: prometheus-redis-exporter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
