apiVersion: v1
kind: Secret
metadata:
  name: users-db-secret
  namespace: monitoring  # Make sure this matches your exporter pod's namespace
type: Opaque
stringData:
  data_source_name: postgresql://postgres:postgres@users-db.full-stack-deployment.svc.cluster.local:5432/users_dev?sslmode=disable
