apiVersion: v1
kind: Secret
metadata:
  name: users-db-secret
  namespace: monitoring
type: Opaque
stringData:
  # DSN for your users_db service in full-stack-deployment
  data_source_name: "postgresql://postgres:postgres@users-db.full-stack-deployment.svc.cluster.local:5432/users_dev?sslmode=disable"
