config:
  datasource:
    host: users-db.full-stack-deployment.svc.cluster.local
    user: postgres
    password: postgres
    database: users_dev
    sslmode: disable

service:
  port: 9187
  targetPort: 9187
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
  labels:
    app: prometheus-postgres-exporter

serviceMonitor:
  enabled: true
  namespace: monitoring
  interval: 15s
  labels:
    release: prometheus
  selector:
    matchLabels:
      app: prometheus-postgres-exporter
  namespaceSelector:
    matchNames:
      - monitoring
