name: CI/CD - Build, Push, and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest



    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push client image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/client:${{env.IMAGE_TAG}} ./services/client
          docker push ${{ secrets.DOCKER_USERNAME }}/client:${{env.IMAGE_TAG}}

      - name: Build and push users image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/users:${{env.IMAGE_TAG}} ./services/users
          docker push ${{ secrets.DOCKER_USERNAME }}/users:${{env.IMAGE_TAG}}

      - name: Build and push nginx image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx:${{env.IMAGE_TAG}} ./services/nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx:${{env.IMAGE_TAG}}

      - name: Build and push users-db image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/users-db:${{env.IMAGE_TAG}} ./services/users/project/db
          docker push ${{ secrets.DOCKER_USERNAME }}/users-db:${{env.IMAGE_TAG}}

  deploy-to-minikube:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set kubectl context (optional)
        run: kubectl config use-context minikube

      - name: Deploy using Helm
        run: |
          helm upgrade --install full-stack-kubernetes ./full-stack-kubernetes \
          --set client.image.tag=${{ env.IMAGE_TAG }} \
          --set users.image.tag=${{ env.IMAGE_TAG }} \
          --set nginx.image.tag=${{ env.IMAGE_TAG }} \
          --set users-db.image.tag=${{ env.IMAGE_TAG }} 
